config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/403', to: 'errors#forbidden', via: :all

  get 'admin/flush_cache', to: 'admin#flush_cache'

  scope '(:locale)', locale: /#{LocalesService.enabled.join("|")}/ do
    resources :subscriptions, only: %i[index]
    get '/unsubscribe/:user_id', controller: :subscriptions, action: :unsubscribe, as: 'subscription_unsubscribe'

    resources :courses, only: %i[index show], path: 'pathways' do
      resources :lessons, only: %i[show], path: 'notes' do
        resource :reaction, only: %i[update destroy] do
          get :set_from_email
        end
      end

      resource :subscription, only: %i[show update destroy] do
        patch :pause
        patch :unpause
      end

      resource :vote, only: %i[create destroy], constraints: { format: :js }
    end

    get  'auth/sign_in'
    post 'auth/callback'
    get  'auth/sign_out'

    resource :profile, only: %i[show update], controller: 'profile'

    resources :pages, only: %i[show]
    root to: 'pages#landing'
  end

  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Ref: https://github.com/mperham/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes
    expected_username, expected_password = ENV.fetch('ADMIN_BASIC_AUTH').split(':')
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(expected_username)) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(expected_password))
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  extend Memoist

  include ErrorHandlers
  include Authentication

  before_action :set_locale

  after_action :set_content_language_header

  protected

  def set_locale
    locale = params[:locale].to_s.strip.to_sym
    LocalesService.current = locale
  end

  def set_content_language_header
    response.headers['Content-Language'] = LocalesService.current
  end

  def default_url_options
    { locale: LocalesService.current }
  end

  def courses_service
    CoursesService.new(STORYBLOK_CLIENT)
  end
  memoize :courses_service

  def pages_service
    PagesService.new(STORYBLOK_CLIENT)
  end
  memoize :pages_service
end

app/helpers/application_helper.rb
module ApplicationHelper
  DEFAULT_IMAGE_META_TAG = 'https://a.storyblok.com/f/50602/200x200/8815278a23/favicon.png'.freeze

  def settings
    SettingsService.new(STORYBLOK_CLIENT).get
  end

  def google_analytics
    return if Rails.application.config.google_analytics_id.blank?

    analytics_id = Rails.application.config.google_analytics_id

    safe_join(
      [
        raw( # rubocop:disable Rails/OutputSafety
          <<-GA
          <script async src="https://www.googletagmanager.com/gtag/js?id=#{analytics_id}"></script>
          <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '#{analytics_id}');

            document.addEventListener('turbo:load', event => {
              if (typeof gtag === 'function') {
                gtag('config', '#{analytics_id}', {
                  'page_location': event.detail.url
                });
              }
            });
          </script>
          GA
        )
      ]
    )
  end

  def default_image_meta_tag
    DEFAULT_IMAGE_META_TAG
  end

  # rubocop:disable Rails/HelperInstanceVariable, Style/RedundantReturn
  def main_container_class
    is_course_page = @course.present? && current_page?(course_path(@course.slug))

    case
    when [courses_path, auth_sign_in_path].include?(request.path) || is_course_page
      return 'container_fluid'
    when !defined?(@page)
      return 'container'
    else
      return ['page-container', @page.full_width ? 'container-fluid' : 'container'].join(' ')
    end
  end
  # rubocop:enable Rails/HelperInstanceVariable, Style/RedundantReturn

  def main_style
    is_courses_index = current_page? courses_path

    return '' unless is_courses_index

    image_url = settings.courses_bg_image

    "background: url('#{image_url}');"
  end

  def params_with_locale(locale)
    request.params.dup.merge(locale: locale)
  end

  # For translated content
  def tc(value)
    value.presence || tag.span('Missing translated content', class: 'missing-translated-content')
  end

  def header_nav_item(text, path, alternate_path: nil, icon_name: nil)
    is_active = current_page? path
    is_active ||= current_page?(alternate_path) if alternate_path
    li_classes = ['nav-item']
    li_classes << 'active' if is_active

    tag.li class: li_classes do
      link_to path, class: 'nav-link' do
        concat(icon(icon_name)) if icon_name
        concat(tag.span(text))
        tag.span(t('site-header.active'), class: 'sr-only') if is_active
      end
    end
  end

  def header_nav_separator
    tag.li ' ', class: 'nav-item nav-link'
  end

  def icon(name, css_class: '', variant: 'fas', size: '1x')
    tag.i '', class: "#{variant} fa-#{name} fa-#{size} #{css_class}"
  end

  def language_class(lang = LocalesService.current)
    "lang-#{lang}"
  end

  def text_direction
    rtl? ? 'rtl' : 'ltr'
  end

  def rtl?
    LocalesService.current_rtl?
  end

  def humanize_boolean(value)
    if value
      t('phrases.yes')
    else
      t('phrases.no')
    end
  end
end

app/views/application/_announcement_banner.html.erb
<% content = settings.announcement_banner %>

<% if content.present? %>
  <div class="alert alert-danger" role="alert">
    <%== content %>
  </div>
<% end %>

app/views/application/_cookie_law.erb
<section id="cookie-law">
  <cookie-law>
  </cookie-law>
</section>

app/views/application/_flash.html.erb
<% flash.each do |key, msg| %>
  <% unless key == :timedout %>
    <%= content_tag :div, class: "flash-alert alert alert-dismissable alert-#{key}" do -%>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
      <%= msg %>
    <% end %>
  <% end %>
<% end %>

app/views/application/_footer.html.erb
<footer class="site-footer">
  <div class="container">
    <div class='row p-5'>
      <div class="col-8">
          <%= link_to 'About us', page_path('about-us') %>
          <br />
          <%= link_to 'Blog', 'https://medium.com/hack-for-chayn' %>
          <br />
          <%= link_to 'Donate', 'https://www.paypal.me/chaynhq' %>
          <br />
          <br />
          <%= link_to 'Facebook', 'https://www.facebook.com/chayn/' %> /
          <%= link_to 'Twitter', 'https://twitter.com/ChaynHQ' %> /
          <%= link_to 'Spotify', 'https://open.spotify.com/show/5QOSUw3m5EQK7lEwtGDYpn' %>
      </div>
    </div>
    <div class='d-flex justify-content-between flex-column flex-md-row'>
      <span>
        © <%= Time.now.year %>, Chayn
      </span>
      <span><%= link_to t('site-footer.privacy-policy'), page_path('privacy-policy') %></span>
      <span><%= link_to t('site-footer.terms-of-service'), page_path('terms-of-service') %></span>
    </div>
  </div>
</footer>

app/views/application/_head.erb
<head>
  <%=
    display_meta_tags(
      site: 'Soul Medicine',
      image_src: default_image_meta_tag,
      reverse: true,
      twitter: {
        card: 'summary',
        site: '@ChaynHQ',
        title: :full_title,
        description:  :description,
        image: :image_src
      },
      og: {
        title: :full_title,
        site_name: :site,
        description: :description,
        image: :image_src
      }
    )
  %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name=viewport content="width=device-width, initial-scale=1">

  <%= favicon_pack_tag 'static/images/favicon.png', type: 'image/png' %>

  <%= google_analytics %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/css?family=Nunito:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <link href="https://bloom.chayn.co/hotjarNPS.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/application/_header.html.erb
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-light pt-0 pb-0 pr-3 pl-3">
    <a class="navbar-brand" href="/">
      <%= vite_image_tag('images/logo.png', class: 'logo d-inline-block align-top', alt: 'Soul Medicine Logo') %>
    </a>
    <h1 class='sr-only'>Soul Medicine</h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse pt-2 pb-2" id="navbarCollapse">
      <ul class="nav navbar-nav navbar-right ml-auto">
        <%= header_nav_item t('site-header.home'), root_path, alternate_path: '/' %>
        <%= header_nav_item t('concepts.course').pluralize, courses_path %>
        <%= header_nav_item t('site-header.about-us'), page_path('about-us') %>

        <%= header_nav_separator %>

        <% if current_user? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarUserDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.display_name %>
            </a>
            <div class="dropdown-menu dropdown-menu-right <%= text_direction -%>" dir="<%= text_direction -%>" aria-labelledby="navbarUserDropdown">
              <%= link_to t('site-header.subscriptions'), subscriptions_path, class: 'dropdown-item' %>
              <%= link_to t('site-header.profile'), profile_path, class: 'dropdown-item' %>
              <%= link_to t('site-header.sign-out'), auth_sign_out_path, class: 'dropdown-item' %>
            </div>
          </li>
        <% else %>
          <%= header_nav_item t('site-header.sign-in'), auth_sign_in_path, icon_name: 'sign-in-alt' %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/application/_languages_selector.html.erb
<div class="text-right mb-2">
  <div class="btn-group" role="group" aria-label="Languages selector">
    <button id="languagesSelectorDropdown" type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= LocalesService.language_name(LocalesService.current) %>
    </button>
    <div class="dropdown-menu dropdown-menu-right <%= text_direction -%>" dir="<%= text_direction -%>" aria-labelledby="languagesSelectorDropdown">
      <% LocalesService.enabled.each do |l| %>
        <% if LocalesService.current == l %>
          <span class="dropdown-item language-dropdown-item" lang="<%= l %>">
            <%= LocalesService.language_name(l) %>
          </span>
        <% else %>
          <%= link_to LocalesService.language_name(l), params_with_locale(l), class: 'dropdown-item language-dropdown-item', lang: l %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/application/_leave_site.html.erb
<leave-site id='leave-site'></leave-site>

app/views/application/_turbo_confirm_modal.html.erb
<template id="turbo-confirm-template">
  <div id="turbo-confirm" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title js-modal-title"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p class="js-modal-body-content"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default js-cancel" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger">Confirm</button>
        </div>
      </div>
    </div>
  </div>
</template>